{"level":"DEBUG","ts":"2023-09-28T10:40:32.840+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T10:40:32.844+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T10:40:32.844+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T10:40:32.845+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T10:41:27.679+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T10:41:27.682+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T10:41:27.683+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T10:41:27.684+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T12:21:36.542+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T12:21:36.543+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T12:21:36.544+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T12:21:36.544+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T12:22:53.308+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T12:22:53.310+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T12:22:53.310+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T12:22:53.310+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T12:23:59.309+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T12:23:59.310+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T12:23:59.311+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T12:23:59.311+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T12:27:09.634+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T12:27:09.635+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T12:27:09.636+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T12:27:09.636+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T15:44:01.888+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T15:44:01.901+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T15:44:01.902+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T15:44:01.902+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T16:00:37.289+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T16:00:37.292+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T16:00:37.293+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T16:00:37.293+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T16:19:49.576+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T16:19:49.577+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T16:19:49.578+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T16:19:49.578+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T16:23:51.802+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T16:23:51.804+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T16:23:51.804+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T16:23:51.804+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T16:29:48.111+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T16:29:48.113+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T16:29:48.114+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T16:29:48.114+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:02:13.543+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:02:13.545+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:02:13.547+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:02:13.547+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:11:18.321+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:11:18.324+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:11:18.325+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:11:18.325+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:29:21.520+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:29:21.522+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:29:21.523+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:29:21.524+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-09-28T17:30:54.222+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:30:58.884+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:30:58.947+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:01.861+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:06.411+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:14.113+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:16.084+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:16.177+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:18.640+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:26.338+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:30.806+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:33.318+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:33.461+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:31:33.761+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:43.071+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:31:46.018+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:46.549+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:50.542+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:50.731+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:55.310+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:31:58.293+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:31:58.814+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:07.577+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:07.765+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:07.983+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:32:10.563+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:11.066+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:19.827+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:24.987+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:25.192+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:31.313+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:32.031+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:42.219+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:42.439+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:43.590+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:44.256+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:55.794+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:56.529+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:59.438+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:32:59.643+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:08.757+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:16.026+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:16.672+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:16.877+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:20.977+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:33:22.781+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:28.241+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:33.278+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:33.956+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T17:33:34.064+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T17:33:34.065+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:37.523+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:41.564+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T17:33:42.308+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:47.220+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:47.284+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:49.745+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T17:33:50.495+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:53.750+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:33:57.917+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:00.467+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:00.498+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:01.956+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:06.163+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:10.158+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:13.753+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:13.811+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:14.422+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:22.734+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:26.503+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:26.972+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:27.111+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:30.985+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:34.697+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:39.258+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:40.268+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:40.346+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:42.932+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T17:34:47.500+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-09-28T17:36:04.729+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:36:27.796+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:36:27.798+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:36:27.799+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:36:27.799+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:40:23.319+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:40:23.322+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:40:23.323+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:40:23.323+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:41:01.838+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:41:01.839+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:41:01.840+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:41:01.840+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:43:00.073+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:43:00.076+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:43:00.077+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:43:00.078+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T17:49:25.240+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T17:49:25.242+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T17:49:25.244+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T17:49:25.244+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:22:30.376+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:22:30.379+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:22:30.379+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:22:30.380+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-09-28T19:25:23.737+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:27.779+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:27.887+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:30.777+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:35.960+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:25:42.669+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:42.983+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:45.021+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:45.070+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:48.160+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:25:54.951+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:25:55.204+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:00.410+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:02.215+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:02.311+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:26:07.164+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:12.643+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:15.472+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:26:19.411+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:19.489+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:19.552+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:24.921+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:27.708+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:36.686+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:36.795+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:37.123+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:39.959+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:49.375+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:53.899+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:26:54.025+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:00.201+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:01.562+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:11.149+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:11.290+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:12.482+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:13.801+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:24.681+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:26.040+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:28.358+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:28.548+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:27:31.627+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:38.250+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:27:43.871+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:44.892+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:45.598+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:45.785+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:50.503+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:27:56.128+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:27:57.144+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:28:00.815+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:01.018+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:01.756+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:05.287+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:28:05.334+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:09.990+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:14.018+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:14.267+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:18.192+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:21.470+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:26.436+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:27.220+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:27.472+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:29.679+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:34.688+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:37.869+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:40.450+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:40.699+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:42.905+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:51.195+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:53.771+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:53.925+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:54.066+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:28:59.453+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:02.308+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:07.016+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:07.189+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:07.677+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:10.524+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:29:13.570+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:15.887+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:20.272+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:20.444+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:29:21.848+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:24.169+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:26.790+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:29:30.109+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:32.454+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:33.571+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:33.648+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:35.027+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:29:38.377+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:40.722+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:43.298+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:46.812+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:46.873+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:29:48.971+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-09-28T19:30:03.939+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:30:24.593+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:30:24.596+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:30:24.597+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:30:24.597+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:35:44.909+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:35:44.911+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:35:44.912+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:35:44.912+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:47:47.626+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:47:47.628+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:47:47.629+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:47:47.629+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-09-28T19:48:40.110+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:48:44.897+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:48:44.959+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:48:47.916+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:48:52.314+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:48:59.902+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:00.106+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:02.161+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:02.225+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:04.539+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:49:12.170+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:12.326+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:16.796+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:19.380+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:19.475+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:49:24.392+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:29.056+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:32.606+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:49:36.669+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:36.685+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:36.716+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:41.263+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:44.913+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:53.430+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:53.938+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:54.016+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:49:57.160+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:05.702+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:11.173+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:11.265+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:17.392+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:17.892+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:28.433+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:28.527+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:29.658+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:30.129+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:41.887+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:42.386+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:45.674+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:45.782+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:50:48.876+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:50:54.640+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:51:01.096+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:02.079+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:02.907+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:02.998+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:06.883+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T19:51:13.364+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:14.315+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T19:51:18.149+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:18.154+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:18.273+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:22.547+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T19:51:22.623+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:26.419+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:31.384+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:31.568+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:34.639+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T19:51:38.757+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-09-28T19:51:53.267+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:52:13.607+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:52:13.609+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:52:13.609+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:52:13.610+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:56:45.583+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:56:45.585+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:56:45.586+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:56:45.586+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:57:16.743+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:57:16.745+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:57:16.745+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:57:16.746+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:58:26.192+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:58:26.193+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:58:26.193+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:58:26.194+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T19:59:12.483+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T19:59:12.486+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T19:59:12.488+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T19:59:12.488+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T20:54:48.391+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T20:54:48.393+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T20:54:48.394+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T20:54:48.394+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T21:04:53.704+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T21:04:53.706+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T21:04:53.706+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T21:04:53.706+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-09-28T21:07:32.079+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:36.120+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:36.182+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:38.012+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:44.384+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:50.247+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:53.341+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:53.389+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:07:56.618+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:02.482+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:08:05.966+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:08.843+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:10.579+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:10.611+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:08:18.249+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:21.034+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:22.684+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:27.890+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:27.906+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:08:30.504+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:33.314+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:34.972+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:08:42.767+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:45.154+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:45.170+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:45.581+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:47.180+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:08:57.840+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:02.377+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:02.377+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:07.463+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:10.017+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:19.609+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:19.625+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:19.721+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:22.257+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:31.923+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:34.502+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:36.803+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:36.819+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:46.741+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:52.115+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:54.044+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:54.059+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:09:54.970+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:09:58.943+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:10:04.339+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-28T21:10:07.224+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-28T21:10:10.171+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:10.280+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:10.312+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:14.545+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:10:16.465+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:18.366+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:23.496+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:23.496+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:10:24.712+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:26.557+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:30.721+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:34.805+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:36.700+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:36.700+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:38.900+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:43.014+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:47.106+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:49.919+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:49.934+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:51.222+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:10:59.474+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:03.169+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:03.184+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:03.263+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:07.672+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:11.524+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:15.927+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:16.405+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:16.436+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:19.698+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:24.112+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:29.632+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:29.648+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:32.303+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:11:32.919+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:35.836+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:40.506+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:11:41.149+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:42.788+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:42.927+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:44.059+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:48.741+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:11:49.309+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:52.288+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:55.980+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:56.093+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:11:56.973+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:11:57.489+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:05.157+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:08.454+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:09.190+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:09.283+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:11.351+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:12.626+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:12.753+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:14.295+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:14.373+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:14.389+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:17.497+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:19.392+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:19.454+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:20.536+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:20.821+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:20.917+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:21.060+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:23.638+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:24.523+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:24.570+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:26.687+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.167+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.307+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.401+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.590+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.698+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:29.777+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:32.806+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:34.712+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:34.805+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:35.904+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:37.512+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:37.651+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:37.761+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:38.941+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:39.867+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:39.915+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:42.051+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:45.001+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:45.017+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:45.158+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:45.877+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:46.002+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:46.111+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:48.243+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:50.070+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:50.131+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:51.272+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:54.226+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:54.335+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:54.335+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:54.428+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:55.182+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:55.213+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:12:57.373+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:12:57.623+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:12:57.764+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:12:57.875+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:12:57.970+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:00.297+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:00.313+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:00.422+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:02.578+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:02.687+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:02.812+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:03.433+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:05.376+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:05.407+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:06.446+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:09.479+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:10.467+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:10.528+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:10.930+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:11.039+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:11.178+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:12.552+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:15.583+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:15.599+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:15.599+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:18.639+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:19.281+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:19.407+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:19.469+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:20.662+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:20.693+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:21.761+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:24.895+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:25.764+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:25.825+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:27.570+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:27.664+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:27.802+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:27.941+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:30.863+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:30.956+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:30.971+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:34.061+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:35.890+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:35.967+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:35.982+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:36.027+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:36.089+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:37.127+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:40.152+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:41.067+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:41.221+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:43.155+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:44.113+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:44.251+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:44.344+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:46.168+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:46.184+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:46.370+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:49.209+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:51.313+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:51.483+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:52.255+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:52.472+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:52.596+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:52.719+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:55.267+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:56.393+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:56.563+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:13:58.104+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:13:58.198+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:13:58.337+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:13:58.383+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:13:58.475+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:00.856+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:00.947+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:01.071+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:01.396+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:01.488+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:01.660+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:04.454+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:06.647+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:06.740+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:07.482+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:09.182+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:09.307+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:09.416+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:10.530+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:11.769+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:11.847+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:13.594+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:16.622+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:16.922+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:16.954+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:17.522+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:17.614+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:17.739+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:19.721+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:22.015+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:22.078+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:22.723+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:25.745+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:25.840+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:25.919+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:26.013+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:27.106+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:27.229+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:28.747+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:31.771+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:32.197+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:32.400+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:34.128+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:34.190+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:34.316+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:34.816+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:37.350+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:37.523+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:37.872+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:40.899+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:42.454+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:42.454+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:42.609+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:42.625+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:42.704+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:43.958+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:46.969+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:47.549+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:47.739+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:50.014+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:50.834+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:50.991+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:51.054+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:52.662+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:52.820+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:53.072+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:56.121+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:57.711+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:57.932+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:14:58.593+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:14:58.721+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:14:58.783+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-28T21:14:58.829+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:59.160+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:59.207+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:59.270+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:14:59.363+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:02.278+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:02.799+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:03.081+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:05.290+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:07.462+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:07.542+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:07.685+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:07.891+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:08.176+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:08.381+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:11.471+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:13.018+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:13.284+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:14.498+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:15.776+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:15.919+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:16.059+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:17.540+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:18.142+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:18.393+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:20.576+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:23.260+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:23.496+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:23.638+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:24.184+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:24.262+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:24.387+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:26.667+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:28.350+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:28.617+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-28T21:15:29.747+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-09-28T21:19:34.645+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T21:20:01.226+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T21:20:01.229+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T21:20:01.230+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T21:20:01.231+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T21:21:00.980+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T21:21:00.981+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T21:21:00.982+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T21:21:00.982+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-28T21:22:01.271+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-28T21:22:01.273+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-28T21:22:01.274+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-28T21:22:01.274+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
