{"level":"DEBUG","ts":"2023-09-24T16:07:16.392+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T16:07:57.706+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T16:07:57.709+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T16:07:57.710+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T16:07:57.711+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T16:08:50.657+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T16:08:50.659+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T16:08:50.660+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T16:08:50.662+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T16:10:26.803+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T16:10:26.806+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T16:10:26.807+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T16:10:26.807+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T18:26:44.840+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T18:26:48.427+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T18:26:48.428+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T18:26:48.428+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T20:22:07.575+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:22:07.577+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:22:07.578+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:22:07.578+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-09-24T20:25:05.231+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:07.964+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:10.172+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:10.172+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:17.462+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:25:19.874+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:20.185+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:27.390+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:27.420+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:29.669+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:25:32.105+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:32.420+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:41.861+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:25:44.343+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:44.610+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:44.688+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:52.692+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:25:54.138+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:25:56.615+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:01.833+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:01.925+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:04.946+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:06.421+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:17.153+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:18.704+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:19.028+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:19.134+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:30.952+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:36.222+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:36.406+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:37.406+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:43.190+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:49.670+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:53.526+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:53.650+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:26:55.447+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:01.941+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:07.669+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:27:08.858+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:10.745+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:10.901+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:19.903+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:27:21.060+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:22.201+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:27.976+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:28.086+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:32.166+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-09-24T20:27:33.307+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:34.477+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-09-24T20:27:42.461+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:27:42.555+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:43.205+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:43.358+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:43.683+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:50.754+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:56.464+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:56.668+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:59.012+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:27:59.945+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:07.288+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:08.161+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:09.739+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:09.944+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:15.450+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:16.360+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:22.988+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:23.190+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:23.692+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:31.895+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:32.613+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:36.203+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:36.489+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:40.137+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:40.843+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:48.350+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:49.100+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:49.488+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:49.736+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:28:50.789+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:28:56.664+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:28:59.038+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:02.773+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:02.975+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:04.913+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:05.347+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:29:07.284+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:13.222+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:13.645+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:29:15.547+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:16.061+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:16.275+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:21.513+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:21.949+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:29.324+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:29.497+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:29.745+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:37.963+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:38.241+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:42.538+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:42.724+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:44.184+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:44.447+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:44.572+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:47.215+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:47.634+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:47.792+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:50.242+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:52.655+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:52.718+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:52.797+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:52.875+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:52.921+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:53.282+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:56.416+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:57.819+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:57.988+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:29:59.428+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:01.011+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:01.088+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:01.180+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:02.474+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:02.874+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:03.121+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:05.543+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:07.974+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:08.204+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:08.622+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:09.285+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:09.361+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:09.454+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:11.634+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:13.077+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:13.325+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:14.725+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:30:15.677+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:30:15.784+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:30:15.939+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:30:16.079+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:17.554+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:17.694+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:17.756+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:17.802+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:18.216+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:18.446+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:20.898+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:23.333+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:23.549+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:23.932+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:25.902+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:25.995+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:26.104+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:26.949+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:28.417+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:28.695+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:30.029+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:33.039+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:33.506+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:33.818+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:34.240+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:34.334+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:34.490+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:36.093+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:38.658+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:38.951+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:39.120+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:42.189+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:42.595+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:42.642+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:42.736+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:43.784+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:44.052+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:45.257+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:48.321+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:48.866+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:49.180+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:50.857+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:50.951+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:51.058+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:51.381+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:53.975+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:54.269+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:54.439+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:57.444+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:59.127+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:59.157+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:59.281+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:59.342+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:30:59.373+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:00.526+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:03.579+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:04.243+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:04.474+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:06.662+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:07.497+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:07.650+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:07.727+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:09.380+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:09.613+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:09.709+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:12.750+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:14.465+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:14.711+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:15.794+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:15.824+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:15.947+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:16.024+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:31:16.177+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:31:16.254+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:31:16.362+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-09-24T20:31:16.453+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:18.849+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:19.603+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:19.790+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:21.888+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.136+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.229+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.352+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.722+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.890+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:24.983+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:28.025+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:29.838+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:29.982+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:31.027+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:32.416+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:32.480+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:32.558+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:34.072+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:34.961+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:35.101+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:37.162+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.058+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.167+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.262+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.699+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.792+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:40.901+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-09-24T20:31:43.352+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-09-24T20:31:54.097+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:32:33.059+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:32:33.063+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:32:33.063+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:32:33.064+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T20:37:35.612+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:37:35.614+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:37:35.614+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:37:35.615+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T20:41:55.757+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:41:55.759+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:41:55.761+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:41:55.761+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T20:42:53.785+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:42:53.787+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:42:53.788+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:42:53.788+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-09-24T20:44:26.470+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-09-24T20:44:26.471+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-09-24T20:44:26.472+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-09-24T20:44:26.472+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
