{"level":"DEBUG","ts":"2023-10-04T16:38:39.137+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T16:39:27.917+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T16:39:27.919+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T16:39:27.919+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T16:39:27.919+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T16:40:32.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:41:32.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:42:32.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:43:32.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:44:32.022+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:45:32.012+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:46:32.006+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:47:32.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:48:32.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:49:32.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:50:32.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T16:51:28.154+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:50965->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T16:52:27.147+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:51003->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T16:53:27.152+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:51061->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T16:54:27.170+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:51109->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T16:55:27.198+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:51157->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"DEBUG","ts":"2023-10-04T16:55:39.624+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T16:55:39.626+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T16:55:39.627+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T16:55:39.628+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T16:56:39.174+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:51235->18.173.121.98:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"DEBUG","ts":"2023-10-04T16:56:59.130+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T16:56:59.132+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T16:56:59.133+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T16:56:59.133+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-10-04T17:12:33.072+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:12:33.074+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:12:33.075+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:12:33.075+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-10-04T17:13:39.336+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:13:39.338+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:13:39.339+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:13:39.339+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:14:44.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:15:44.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:16:44.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:17:41.771+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:17:41.772+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:17:41.773+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:17:41.774+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:18:46.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:19:46.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:20:46.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:21:05.504+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:21:05.505+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:21:05.506+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:21:05.506+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:22:10.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:23:10.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:24:10.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:25:10.002+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:26:16.070+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:26:16.072+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:26:16.073+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:26:16.073+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-10-04T17:27:29.396+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:27:29.397+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:27:29.398+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:27:29.398+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:28:34.007+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:29:34.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:30:34.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:31:34.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:32:34.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:33:25.120+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:33:25.122+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:33:25.122+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:33:25.122+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:34:30.022+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:35:12.363+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:35:12.365+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:35:12.365+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:35:12.366+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:36:17.009+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:37:17.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:38:17.024+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:39:17.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:40:54.138+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:40:54.141+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:40:54.142+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:40:54.142+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-10-04T17:42:46.048+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:42:46.049+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:42:46.050+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:42:46.050+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T17:43:51.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:44:51.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:45:51.012+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:46:51.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:47:51.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:48:51.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:49:51.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T17:50:51.023+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T17:51:32.496+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T17:51:32.499+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T17:51:32.500+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T17:51:32.500+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"DEBUG","ts":"2023-10-04T18:03:58.300+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T18:03:58.302+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T18:03:58.302+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T18:03:58.302+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T18:05:03.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:06:03.009+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:07:03.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:08:03.002+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T18:08:15.372+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T18:08:15.373+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T18:08:15.374+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T18:08:15.374+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T18:09:20.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:10:20.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:11:20.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:12:20.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:13:20.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:14:20.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:15:20.006+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:16:20.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T18:17:20.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T20:35:56.303+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T20:35:56.305+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T20:35:56.306+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T20:35:56.306+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T20:36:09.484+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:13.511+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:13.558+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:16.530+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:21.674+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:28.781+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:30.777+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:30.777+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:33.896+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:40.992+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:46.111+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:47.992+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:48.024+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:36:58.399+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:01.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:37:01.235+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:05.231+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:05.263+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-10-04T20:37:08.547+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:10.718+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:13.491+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-10-04T20:37:20.835+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:22.515+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:22.515+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:22.954+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:25.738+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-10-04T20:37:33.060+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:35.138+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:39.700+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:39.779+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"WARN","ts":"2023-10-04T20:37:45.287+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:46.015+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:47.321+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:56.956+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:57.033+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:58.267+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:37:59.567+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:01.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:38:10.463+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:11.799+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:14.176+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:14.256+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:24.050+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:30.699+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:31.401+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:31.479+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:36.355+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:42.904+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:48.583+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:48.662+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:48.725+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: i/o timeout"}
{"level":"ERROR","ts":"2023-10-04T20:38:54.210+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:38:56.518+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:38:58.807+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:01.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:39:01.826+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:01.921+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:39:04.719+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:07.059+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:10.490+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:39:12.975+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:15.079+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:15.113+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:15.297+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:18.736+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:39:21.149+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:23.496+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:26.934+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:28.254+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:28.300+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:31.714+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:39.886+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:41.513+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:41.560+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:43.149+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:48.134+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:51.404+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:54.733+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:54.828+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:56.365+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:39:59.574+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:01.017+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:40:04.542+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:07.991+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:08.086+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:12.735+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:15.732+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:20.917+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:21.103+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:21.309+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:23.897+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:29.090+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:40:29.345+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:32.082+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:34.334+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:34.503+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:37.321+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:40:37.556+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:45.495+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:40:45.697+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:47.523+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:47.696+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:48.264+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:52.421+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:52.498+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:52.639+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:52.827+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:53.661+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:40:53.892+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:56.681+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:57.767+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:57.908+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:40:59.738+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:00.602+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:00.713+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:00.776+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:01.012+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:41:02.823+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:02.838+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:03.059+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:05.930+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:07.941+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:08.180+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:08.889+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:09.014+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:09.014+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:09.107+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:12.118+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:13.033+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:13.270+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:15.210+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:17.258+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:17.383+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:17.478+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:18.151+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:18.230+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:18.324+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:21.272+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:23.254+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:23.428+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:24.317+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:25.601+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:25.695+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:25.756+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:27.450+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:28.380+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:28.584+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:30.543+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:33.481+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:33.621+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:33.669+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:33.855+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:33.981+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:34.059+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:36.675+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:38.606+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:38.781+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:39.683+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:42.173+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:42.236+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:42.347+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:42.774+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:43.688+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:43.877+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:45.824+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:48.831+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:48.831+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:48.958+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:50.486+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:50.564+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:50.690+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:51.927+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:41:53.957+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:53.972+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:41:54.066+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:54.082+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:41:54.160+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:41:54.236+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:55.006+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:58.012+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:58.797+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:58.923+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:59.016+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:59.079+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:41:59.221+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:01.025+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:42:01.150+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:04.155+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:04.203+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:04.329+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:07.156+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:07.233+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:07.281+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:07.390+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:09.309+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:09.482+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:10.257+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:13.322+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:14.399+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:14.618+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:15.475+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:15.568+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:15.694+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:16.445+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:19.506+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:19.522+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:19.694+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:22.569+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:23.805+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:23.900+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:24.010+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:24.652+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:24.793+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:25.598+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:28.612+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:29.770+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:29.864+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:31.666+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:32.102+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:32.196+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:32.351+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:34.691+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:34.879+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:34.988+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:37.733+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.025+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.104+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.479+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.556+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.681+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:40.807+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:43.842+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:45.148+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:45.242+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:46.938+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:48.853+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:48.980+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:49.121+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:49.968+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:50.266+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:50.405+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:53.052+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:42:54.314+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:42:54.406+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:42:54.500+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:42:54.594+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:55.380+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:55.505+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:56.067+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:57.194+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:57.288+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:57.398+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:42:59.131+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:00.458+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:00.585+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:01.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:43:02.165+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.204+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.469+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.578+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.624+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.670+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:05.701+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:08.240+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:10.655+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:10.826+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:11.278+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:13.813+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:13.938+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:14.048+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:14.392+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:15.750+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:15.940+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:17.422+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:20.423+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:20.847+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:21.034+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:22.151+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:22.277+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:22.370+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:23.437+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:25.926+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:26.131+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:26.445+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:29.520+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:30.427+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:30.506+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:30.633+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:31.012+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:31.234+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:32.597+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:35.657+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:36.157+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:36.360+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:38.707+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:38.738+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:38.848+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:38.975+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:41.218+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:41.484+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:41.716+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:44.828+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:46.336+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:46.605+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:47.134+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:47.243+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:47.322+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:47.866+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:50.895+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:51.462+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:51.715+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:53.991+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:43:54.715+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:43:54.794+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:43:54.937+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:43:55.046+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:55.444+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:55.570+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:55.679+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:56.575+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:56.811+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:43:57.080+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:00.089+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:01.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:44:01.644+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:01.911+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:03.160+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:03.807+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:03.902+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:04.013+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:06.263+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:06.793+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:06.996+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:09.381+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:11.934+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:12.122+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:12.137+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:12.295+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:12.405+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:12.515+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:15.545+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:17.031+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:17.232+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:18.590+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:20.523+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:20.585+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:20.663+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:21.647+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:22.115+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:22.351+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:24.697+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:27.220+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:27.504+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:27.738+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:28.774+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:28.853+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:28.963+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:30.749+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:32.364+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:32.600+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:33.757+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:36.797+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:37.081+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:37.173+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:37.282+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:37.472+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:37.676+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:39.910+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:42.559+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:42.811+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:42.984+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:45.376+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:45.470+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:45.533+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:46.071+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:47.651+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:47.951+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:49.127+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:52.149+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:52.751+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:53.064+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:53.615+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:53.695+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:53.774+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:44:55.130+0800","caller":"log/log.go:169","msg":"recoverer: could not list lease expired tasks: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:55.176+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:44:55.207+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:44:55.287+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"WARN","ts":"2023-10-04T20:44:55.444+0800","caller":"log/log.go:169","msg":"recoverer: could not reclaim stale aggregation sets in queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:57.837+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:58.196+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:44:58.211+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:01.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:45:01.303+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:01.918+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:02.041+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:02.136+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:02.960+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:03.307+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:04.334+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:07.472+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:08.068+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:08.459+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:10.250+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:10.391+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:10.502+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:10.518+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:13.181+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:13.527+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:13.543+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:16.664+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:18.308+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:18.574+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:18.652+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:18.715+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:18.778+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:19.722+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:22.739+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:23.461+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:23.777+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:25.814+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:26.891+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:26.985+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:27.109+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:28.586+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:28.834+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:28.850+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:31.853+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:33.724+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:33.945+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:34.887+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:35.215+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:35.325+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:35.418+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:37.953+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:38.797+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:39.065+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:40.970+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:43.530+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"critical\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:43.638+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:43.717+0800","caller":"log/log.go:176","msg":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:43.919+0800","caller":"log/log.go:176","msg":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:44.060+0800","caller":"log/log.go:176","msg":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"ERROR","ts":"2023-10-04T20:45:44.140+0800","caller":"log/log.go:176","msg":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it."}
{"level":"DEBUG","ts":"2023-10-04T20:45:52.583+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T20:47:29.883+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T20:47:29.885+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T20:47:29.885+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T20:47:29.885+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T20:48:34.017+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:49:34.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:50:34.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:51:34.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:52:34.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:53:34.024+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:54:34.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:55:34.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:56:34.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:57:34.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:58:34.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T20:59:34.002+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:00:34.009+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:01:34.002+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:02:34.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:03:34.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:04:34.006+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:05:34.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:06:34.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:07:34.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:08:34.023+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:09:34.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:10:34.012+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:11:34.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:12:34.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:13:34.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:14:34.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:15:34.022+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:16:34.019+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:17:34.026+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T21:18:34.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T22:24:20.253+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T22:24:20.254+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T22:24:20.256+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T22:24:20.256+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T22:25:25.004+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:26:25.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:27:25.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:28:25.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:29:25.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:30:25.017+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:31:25.022+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:32:25.012+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:33:25.022+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:34:25.020+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:35:25.009+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:36:25.017+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:37:25.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:38:25.001+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:39:25.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:40:25.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:41:25.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:42:25.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:43:25.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:44:25.023+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:45:25.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:46:25.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:47:25.008+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:48:25.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:49:25.017+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:50:25.007+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T22:51:20.152+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55126->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:52:20.153+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55181->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:53:20.169+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55241->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:54:20.147+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55297->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:55:20.160+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55356->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:56:20.182+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55416->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:57:20.160+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55474->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:58:20.163+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55534->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T22:59:20.157+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55589->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T23:00:20.169+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": read tcp 192.168.2.2:55649->18.154.144.82:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"level":"ERROR","ts":"2023-10-04T23:01:25.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:02:25.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:03:25.024+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:04:25.014+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:05:25.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:06:25.006+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:07:25.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:08:25.016+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:09:25.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:10:25.007+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:11:25.011+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:12:25.015+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T23:15:02.183+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T23:15:02.184+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T23:15:02.185+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T23:15:02.185+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
{"level":"ERROR","ts":"2023-10-04T23:16:07.021+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:17:07.018+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:18:07.013+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:19:07.010+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"ERROR","ts":"2023-10-04T23:20:07.007+0800","caller":"task/usdt_rate_job.go:43","msg":"usdt rate get err:Get \"https://api.coinmarketcap.com/data-api/v3/cryptocurrency/detail/chart?convertId=2787&id=825&range=1H\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"DEBUG","ts":"2023-10-04T23:20:58.963+0800","caller":"dao/mdb.go:46","msg":"[store_db] mysql connDB success"}
{"level":"DEBUG","ts":"2023-10-04T23:20:58.964+0800","caller":"dao/rdb.go:39","msg":"[store_redis] redis connRdb success,suc=%sPONG"}
{"level":"INFO","ts":"2023-10-04T23:20:58.965+0800","caller":"log/log.go:162","msg":"Starting processing"}
{"level":"INFO","ts":"2023-10-04T23:20:58.965+0800","caller":"log/log.go:162","msg":"Send signal TERM or INT to terminate the process"}
